# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from __future__ import unicode_literals
from lino.api import _
help_texts = {
    'lino_presto.projects.psico.settings.demo.Site' : _("""Defines and instantiates a demo version of Lino Care."""),
}
